name: ek_sheba
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  
  go_router: ^8.0.5
  google_fonts: ^5.1.0
  loading_animation_widget: ^1.2.0+4
  collection: ^1.17.1
  url_launcher: ^6.1.11
  get_it: ^7.6.0
  http: ^1.1.0
  flutter_cached_pdfview: ^0.4.2
  decimal: ^2.3.3
  my_utils:
    git: https://github.com/yeasin50/my_utils.git
  fpdart: ^1.1.0
  flutter_secure_storage: ^8.0.0
  patch_pal:
    git:
      url: https://github.com/yeasin50/patch_pal.git
      ref: master
  path_provider: ^2.1.1
  flutter_pdfview: ^1.3.1
  dio: ^5.3.2
 

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  flutter_gen_runner: ^5.3.1
 
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  change_app_package_name: ^1.1.0
  pspdfkit_flutter: ^3.6.0


flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/logo/logo.png
  