name: build-upload

on:
  push:
    branches:
      - deploy

jobs:
  build_upload:
    name: Build and Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get Branch Name
        id: get_branch_name
        run: echo "name=branch::$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT

      - name: Get Today's Date
        id: get_date
        run: echo "name=date::$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get Folder id by condition
        uses: haya14busa/action-cond@v1
        id: folder_id
        with:
          cond: ${{ steps.branch.outputs.branch == 'deploy' }}
          if_true: ${{secrets.MASTER_FOLDER_ID}}

    #   - run: flutter pub get
    #   - run: flutter build apk --release
