name: Build iOS App

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - master

jobs:
  build-ios:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"

   #This snippet that helped me was borrowed from https://gist.github.com/devhammed/617d920b7ee886591a46c22633ab0093
      - name: Build iOS App
        run: |
            flutter build ios --profile --no-codesign
            cd build/ios/iphoneos
            mkdir Payload
            cd Payload
            ln -s ../Runner.app
            cd ..
            zip -r app.ipa Payload
    
      # Upload generated ipa to the artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: build/ios/iphoneos/app.ipa 
